-- Subscription Plans
CREATE TABLE public.subscription_plans (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  price numeric NOT NULL DEFAULT 0,
  tier text NOT NULL DEFAULT 'basic',
  features text[] DEFAULT '{}'::text[],
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.subscription_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view active plans" ON public.subscription_plans
  FOR SELECT TO public USING (is_active = true);

CREATE POLICY "Admins can manage plans" ON public.subscription_plans
  FOR ALL TO authenticated USING (has_role(auth.uid(), 'admin'));

-- User Subscriptions
CREATE TABLE public.user_subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  plan_id uuid NOT NULL REFERENCES public.subscription_plans(id),
  status text NOT NULL DEFAULT 'active',
  starts_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.user_subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own subscriptions" ON public.user_subscriptions
  FOR SELECT TO authenticated USING (user_id = auth.uid());

CREATE POLICY "Admins can manage subscriptions" ON public.user_subscriptions
  FOR ALL TO authenticated USING (has_role(auth.uid(), 'admin'));

-- Workout Plans (generated by AI)
CREATE TABLE public.workout_plans (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  goal text NOT NULL,
  level text NOT NULL DEFAULT 'iniciante',
  duration_weeks integer NOT NULL DEFAULT 4,
  plan_data jsonb NOT NULL DEFAULT '{}',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.workout_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own workout plans" ON public.workout_plans
  FOR ALL TO authenticated USING (user_id = auth.uid());

CREATE POLICY "Admins can view all workout plans" ON public.workout_plans
  FOR SELECT TO authenticated USING (has_role(auth.uid(), 'admin'));

-- Exercise Library
CREATE TABLE public.exercises (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  muscle_group text NOT NULL,
  category text NOT NULL,
  description text,
  gif_url text,
  muscle_highlight_url text,
  equipment text,
  difficulty text DEFAULT 'intermediario',
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.exercises ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view exercises" ON public.exercises
  FOR SELECT TO public USING (true);

CREATE POLICY "Admins can manage exercises" ON public.exercises
  FOR ALL TO authenticated USING (has_role(auth.uid(), 'admin'));

-- Workout Chat Messages
CREATE TABLE public.workout_chat_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  workout_plan_id uuid REFERENCES public.workout_plans(id) ON DELETE SET NULL,
  role text NOT NULL,
  content text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.workout_chat_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own chat messages" ON public.workout_chat_messages
  FOR ALL TO authenticated USING (user_id = auth.uid());

-- Insert default subscription plans
INSERT INTO public.subscription_plans (name, slug, description, price, tier, features) VALUES
  ('Básico', 'basico', 'Acesso a treinos personalizados por IA e conteúdo educacional básico.', 49.90, 'basic', 
   ARRAY['Treinos personalizados por IA', 'Biblioteca de exercícios com GIFs', 'Rotina mensal automatizada', 'Conteúdo educacional básico']),
  ('Intermediário', 'intermediario', 'Tudo do Básico + protocolos avançados de suplementação e dietas personalizadas.', 149.90, 'intermediate', 
   ARRAY['Tudo do plano Básico', 'Protocolos avançados de suplementação', 'Dietas personalizadas', 'Chat com agente de IA ilimitado', 'Análise de composição corporal']),
  ('Premium', 'premium', 'Experiência completa com consultoria profissional, análise de exames e acompanhamento dedicado.', 349.90, 'premium', 
   ARRAY['Tudo do plano Intermediário', 'Consultoria com profissionais', 'Análise de exames laboratoriais', 'Realização de exames com profissionais', 'Acompanhamento personalizado', 'Acesso prioritário a eventos']);